global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    earth:
        type: cosmos
        value:
            key-directory: keys/earth
            key: bob
            chain-id: earth
            rpc-addr: http://127.0.0.1:26657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 1stake
            min-gas-amount: 100000
            max-gas-amount: 10000000
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    mars:
        type: cosmos
        value:
            key-directory: keys/mars
            key: bob
            chain-id: mars
            rpc-addr: http://127.0.0.1:26659
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 1stake
            min-gas-amount: 100000
            max-gas-amount: 10000000
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    blog-earth-mars-new:
        src:
            chain-id: earth
            client-id: 07-tendermint-0
            connection-id: connection-2
        dst:
            chain-id: mars
            client-id: 07-tendermint-0
            connection-id: connection-2
        src-channel-filter:
            rule: ""
            channel-list: []
    earth-mars:
        src:
            chain-id: earth
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: mars
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: ""
            channel-list: []
